version: '2'
services:
  plex:
    image: linuxserver/plex
    environment:
      - VERSION=latest
      - PUID=${PUID}
      - PGID=${PGID}
    ports:
      - ${PORT}
    volumes:
      - plex_config:/config
      - plex_data:/data
    network_mode: ${NET}
    labels:
      io.rancher.container.pull_image: always
      io.rancher.container.dns: 'true'
  samba:
    image: dperson/samba
    environment:
      - USERID=${PUID}
      - GROUPID=${PGID}
    command:
      - "samba.sh"
      - "-u"
      - "plex;plexpassword"
      - "-s"
      - "plexdata;/data;yes;no;yes"
      - "-s"
      - "plexconfig;/config;yes;no;yes"
    volumes:
      - plex_config:/config
      - plex_data:/data
    network_mode: ${NET}
    ports:
      - "137:137/udp"
      - "138:138/udp"
      - "139:139"
      - "445:445"
volumes:
  plex_config:
  plex_data:
    driver: rancher-nfs
